services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./movie_data:/app/data
    restart: unless-stopped
    container_name: web
    networks:
      - movie-network

  test:
    image: swsyspro-test-engine:2025-v3
    environment:
      SWSYSPRO_TEST_ENGINE_HOST: http://web:8080
    depends_on:
      - web
    networks:
      - movie-network

volumes:
  movie_data:

networks:
  movie-network:
    driver: bridge
