services:
  movie-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./movie_data:/app/data
    restart: unless-stopped
    container_name: movie-api
    networks:
      - movie-network

  test:
    image: test-engine:v2
    environment:
      SWSYSPRO_TEST_ENGINE_HOST: http://movie-api:8080/
    depends_on:
      - movie-api
    networks:
      - movie-network

volumes:
  movie_data:

networks:
  movie-network:
    driver: bridge
